name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Code quality
      run: |
        black --check --line-length 120 app/ tests/
        isort --check-only --profile black app/ tests/
        flake8 app/ tests/ --max-line-length=120 --extend-ignore=E203,W503
        
    - name: Run tests
      run: pytest tests/ -v
